### ISSUE TITLE
Downloading the caffe model

### ISSUE THREAD

**Issue by Yaneke** [jasonlovescoding/YOLOv3-caffe#2]
Hello Jason,
Thank you for your work, I have been looking for such a file for quite some time :)
However, I could not download it until now, mainly because I do not understand Chinese (even though I tried to use Google Translate to help me out), and the GitHub login does not seem to work for me...
Thanks a lot!

**Comment by jasonlovescoding** [comment]
Hi @Yaneke 
I've shared a google drive link in the new README, so you should be able to download from there now.
Good luck! ;)

**Comment by Yaneke** [comment]
Thank you very much!
