### ISSUE TITLE
caffe.ConvolutionParameter" has no field named "hole_h

### ISSUE THREAD

**Issue by 15151874182** [jasonlovescoding/YOLOv3-caffe#4]
My enviroment:
Ubuntu18.04
python3
caffe 1.00

 Hello,@jasonlovescoding ,when i tested the 'detect_one.py', the error show that  'caffe.ConvolutionParameter" has no field named "hole_h'.The prototxt i used was download from the url you told in Readme. And i checked the source code of  caffe.ConvolutionParameter,it has no description of 'hole_h &hole_w' which were shown in the prototxt file.The prototxt file and error message are as below:

layer {
  name: "Convolution0"
  type: "Convolution"
  bottom: "data"
  top: "369"
  convolution_param {
    num_output: 32
    bias_term: false
    group: 1
    pad_h: 1
    pad_w: 1
    kernel_h: 3
    kernel_w: 3
    stride_h: 1
    stride_w: 1
    hole_h: 1
    hole_w: 1
  }
}

cty@ubuntu:/mnt/hgfs/YOLOv3-caffe-master$ python3 detect_one.py 
#############
#############
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0128 01:29:10.730391  2398 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0128 01:29:10.730473  2398 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0128 01:29:10.730481  2398 _caffe.cpp:142] Net('model/yolov3.prototxt', 1, weights='model/yolov3.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 23:11: Message type "caffe.ConvolutionParameter" has no field named "hole_h".
F0128 01:29:10.733765  2398 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: model/yolov3.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

wish ur help,many thx

**Comment by jasonlovescoding** [comment]
Hi,
sorry for the confusion - the transformation I wrote was for a different branch of caffe. To work with BVLC caffe, please use the downloaded caffemodel with the prototxt file from the original project files, instead of the downloaded one.

**Comment by 15151874182** [comment]
> Hi,
> sorry for the confusion - the transformation I wrote was for a different branch of caffe. To work with BVLC caffe, please use the downloaded caffemodel with the prototxt file from the original project files, instead of the downloaded one.

**Comment by 15151874182** [comment]
> Hi,
> sorry for the confusion - the transformation I wrote was for a different branch of caffe. To work with BVLC caffe, please use the downloaded caffemodel with the prototxt file from the original project files, instead of the downloaded one.

thank you for your reply,it works well with another prototxt in ' YOLOv3-caffe-mergebn' mentioned in your Readme .
